name: Auto-Update M3U Playlist

on:
  workflow_dispatch:
  repository_dispatch:
    types: [force_update]

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Python Script
        run: python update.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add live.m3u
          git commit -m "Auto-update live.m3u playlist" || exit 0
          git push
